-- ==========================================
-- E-COMMERCE SALES ANALYSIS
-- SQL PROJECT
-- ==========================================

-- Tools Used:
-- MySQL
-- MySQL Workbench
-- Microsoft Excel

-- Query 1: Overall Business Performance
SELECT SUM(REVENUE) AS TOTAL_REVENUE,
       SUM(PROFIT) AS TOTAL_PROFIT,
       COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS;
SELECT CATEGORY,
       SUM(REVENUE) AS TOTAL_REVENUE,
       SUM(PROFIT) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY CATEGORY
ORDER BY TOTAL_REVENUE DESC;
SELECT PRODUCT,
       SUM(REVENUE) AS TOTAL_REVENUE,
       SUM(PROFIT) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY PRODUCT
ORDER BY TOTAL_REVENUE DESC;
SELECT C.CUSTOMER_NAME,
       SUM(O.REVENUE) AS TOTAL_REVENUE
FROM ORDERS O
INNER JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;
SELECT PRODUCT,
       SUM(REVENUE) AS TOTAL_REVENUE
FROM ORDERS
GROUP BY PRODUCT
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;
SELECT CATEGORY,
       SUM(PROFIT) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY CATEGORY
ORDER BY TOTAL_PROFIT DESC;
SELECT PAYMENT_METHOD,
       SUM(REVENUE) AS TOTAL_REVENUE
FROM ORDERS
GROUP BY PAYMENT_METHOD
ORDER BY TOTAL_REVENUE DESC;
SELECT REGION,
       SUM(REVENUE) AS TOTAL_REVENUE,
       SUM(PROFIT) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY REGION
ORDER BY TOTAL_REVENUE DESC;
SELECT C.CUSTOMER_NAME,
       COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_ORDERS DESC;
SELECT DATE_FORMAT(ORDER_DATE, '%Y-%m') AS SALES_MONTH,
       SUM(REVENUE) AS TOTAL_REVENUE,
       SUM(PROFIT) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY SALES_MONTH
ORDER BY SALES_MONTH;
WITH PRODUCT_TOTALS AS (
    SELECT CATEGORY,
           PRODUCT,
           SUM(REVENUE) AS TOTAL_REVENUE
    FROM ORDERS
    GROUP BY CATEGORY, PRODUCT
),
RANKED_PRODUCTS AS (
    SELECT CATEGORY,
           PRODUCT,
           TOTAL_REVENUE,
           RANK() OVER (
               PARTITION BY CATEGORY
               ORDER BY TOTAL_REVENUE DESC
           ) AS PRODUCT_RANK
    FROM PRODUCT_TOTALS
)
SELECT *
FROM RANKED_PRODUCTS
WHERE PRODUCT_RANK = 1;
WITH CUSTOMER_TOTALS AS (
    SELECT C.CUSTOMER_NAME,
           SUM(O.REVENUE) AS TOTAL_REVENUE,
           SUM(O.PROFIT) AS TOTAL_PROFIT
    FROM CUSTOMERS C
    INNER JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY C.CUSTOMER_NAME
)
SELECT CUSTOMER_NAME,
       TOTAL_REVENUE,
       TOTAL_PROFIT,
       (TOTAL_PROFIT / TOTAL_REVENUE) * 100 AS PROFIT_MARGIN
FROM CUSTOMER_TOTALS
ORDER BY PROFIT_MARGIN DESC;
WITH CUSTOMER_TOTALS AS (
    SELECT C.CUSTOMER_NAME,
           SUM(O.REVENUE) AS TOTAL_REVENUE
    FROM CUSTOMERS C
    INNER JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
    GROUP BY C.CUSTOMER_NAME
)
SELECT CUSTOMER_NAME,
       TOTAL_REVENUE,
       RANK() OVER (
           ORDER BY TOTAL_REVENUE DESC
       ) AS REVENUE_RANK
FROM CUSTOMER_TOTALS;
SELECT CUSTOMER_ID,
       ORDER_ID,
       REVENUE,
       SUM(REVENUE) OVER (
           PARTITION BY CUSTOMER_ID
           ORDER BY ORDER_ID
       ) AS RUNNING_TOTAL
FROM ORDERS;
SELECT CUSTOMER_ID,
       ORDER_ID,
       REVENUE,
       LAG(REVENUE) OVER (
           PARTITION BY CUSTOMER_ID
           ORDER BY ORDER_ID
       ) AS PREVIOUS_REVENUE
FROM ORDERS;
SELECT CUSTOMER_ID,
       ORDER_ID,
       REVENUE,
       LEAD(REVENUE) OVER (
           PARTITION BY CUSTOMER_ID
           ORDER BY ORDER_ID
       ) AS NEXT_REVENUE
FROM ORDERS;
SELECT CUSTOMER_ID,
       ORDER_ID,
       REVENUE,
       AVG(REVENUE) OVER (
           PARTITION BY CUSTOMER_ID
           ORDER BY ORDER_ID
           ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
       ) AS MOVING_AVERAGE
FROM ORDERS;
SELECT CUSTOMER_ID,
       ORDER_ID,
       REVENUE,
       SUM(REVENUE) OVER (
           PARTITION BY CUSTOMER_ID
       ) AS CUSTOMER_TOTAL_REVENUE
FROM ORDERS;
SELECT C.CUSTOMER_NAME
FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE O.ORDER_ID IS NULL;
SELECT ORDER_ID,
       PRODUCT,
       REVENUE,
       PROFIT
FROM ORDERS
WHERE CATEGORY = 'ELECTRONICS'
  AND REVENUE > 20000
ORDER BY REVENUE DESC;
SELECT REGION,
       AVG(PROFIT) AS AVERAGE_PROFIT
FROM ORDERS
GROUP BY REGION
ORDER BY AVERAGE_PROFIT DESC;
SELECT PAYMENT_METHOD,
       AVG(REVENUE) AS AVG_REVENUE
FROM ORDERS
GROUP BY PAYMENT_METHOD
ORDER BY AVG_REVENUE DESC;
SELECT ORDER_ID,
       CUSTOMER_ID,
       PRODUCT,
       REVENUE,
       PROFIT
FROM ORDERS
WHERE REVENUE > (
    SELECT AVG(REVENUE)
    FROM ORDERS
)
ORDER BY REVENUE DESC;
SELECT CUSTOMER_ID,
       ORDER_ID,
       PRODUCT,
       REVENUE
FROM ORDERS O
WHERE REVENUE > (
    SELECT AVG(O2.REVENUE)
    FROM ORDERS O2
    WHERE O2.CUSTOMER_ID = O.CUSTOMER_ID
)
ORDER BY CUSTOMER_ID, REVENUE DESC;
SELECT CATEGORY,
       SUM(REVENUE) AS TOTAL_REVENUE,
       SUM(PROFIT) AS TOTAL_PROFIT,
       (SUM(PROFIT) / SUM(REVENUE)) * 100 AS PROFIT_MARGIN
FROM ORDERS
GROUP BY CATEGORY
ORDER BY PROFIT_MARGIN DESC;
SELECT C.CUSTOMER_NAME,
       SUM(O.PROFIT) AS TOTAL_PROFIT
FROM ORDERS O
INNER JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_PROFIT DESC
LIMIT 3;
SELECT CATEGORY,
       REGION,
       SUM(REVENUE) AS TOTAL_REVENUE,
       SUM(PROFIT) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY CATEGORY, REGION
ORDER BY TOTAL_REVENUE DESC;
SELECT DATE_FORMAT(ORDER_DATE, '%Y-%m') AS SALES_MONTH,
       COUNT(ORDER_ID) AS TOTAL_ORDERS,
       SUM(REVENUE) AS TOTAL_REVENUE
FROM ORDERS
GROUP BY SALES_MONTH
ORDER BY SALES_MONTH;
SELECT C.CUSTOMER_NAME,
       SUM(O.REVENUE) AS TOTAL_REVENUE,
       SUM(O.PROFIT) AS TOTAL_PROFIT,
       COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS C
INNER JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;
